server:
  port: 9003
spring:
  application:
    name: tensquare-qa
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_qa?serverTimezone=UTC
    username: root
    password: 6200870
  jpa:
    database: MySQL
    show-sql: true
jwt:
  config:
    key: itcast
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true